USE [master]
GO
/****** Object:  Database [PROYECTO_PROGRA3]    Script Date: 03/06/2020 15:03:11 ******/
CREATE DATABASE [PROYECTO_PROGRA3]
GO
USE [PROYECTO_PROGRA3];
GO
/****** Object:  Table [ROL]    Script Date: 03/06/2020 15:03:11 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [ROL](
	[ID_ROL] [int] NOT NULL,
	[NOMBRE] [varchar](50) NULL,
	[DESCRIPCION] [varchar](50) NULL,
	[ACTIVO] [int] NULL,
	[USUARIO_CREA] [varchar](50) NULL,
	[USUARIO_MOD] [varchar](50) NULL,
	[FECHA_CREA] [varchar](50) NULL,
	[FECHA_MOD] [varchar](50) NULL,
 CONSTRAINT [PK_ROL] PRIMARY KEY CLUSTERED 
(
	[ID_ROL] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
SELECT*FROM [ROL];
GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [USUARIO]  ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING OFF
GO
CREATE TABLE [USUARIO](
	[ID_USUARIO] [int] NOT NULL,
	[NOMBRE] [varchar](80) NULL,
	[APELLIDO] [varchar](80) NULL,
	[USUARIO] [varchar](80) NOT NULL,
	[PASSWORD] [varchar](80) NULL,
	[ID_ROL] [int] NOT NULL,
	[FECHA_CREA] [varchar](50) NULL,
	[ACTIVO] [int] NULL,
	[FECHA_MOD] [varchar](50) NULL,
	[USUARIO_CREA] [varchar](50) NULL,
	[USUARIO_MOD] [varchar](50) NULL,
	[CODIGO] [varchar](50) NULL,
 CONSTRAINT [PK_USUARIO] PRIMARY KEY CLUSTERED 
(
	[ID_USUARIO] ASC,
	[ID_ROL] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]
SELECT*FROM [USUARIO];

GO
SET ANSI_PADDING OFF
GO
/****** Object:  Table [PERMISO]    Script Date: 03/06/2020 15:03:11 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [PERMISO](
	[ID_PERMISO] [int] NOT NULL,
	[ID_MODULO] [int] NOT NULL,
	[ID_ROL] [int] NOT NULL,
	[FECHA_CREA] [varchar](50) NULL,
	[FECHA_MOD] [varchar](50) NULL,
	[USUARIO_CREA] [varchar](50) NULL,
	[USUARIO_MOD] [varchar](50) NULL,
	[ACTIVO] [int] NULL,
 CONSTRAINT [PK_PERMISO] PRIMARY KEY CLUSTERED 
(
	[ID_PERMISO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
SELECT*FROM [PERMISO];

/****** Object:  Table [PEDIDO]    Script Date: 03/06/2020 15:03:11 ******/
SET ANSI_NULLS ON
GO
SET QUOTED_IDENTIFIER ON
GO
SET ANSI_PADDING ON
GO
CREATE TABLE [MODULO](
	[ID_MODULO] [int] NOT NULL,	
	[NOMBRE] [varchar](50) NOT NULL,
	[DESCRIPCION] [varchar](50) NOT NULL,
	[PATH] [varchar](50) NULL,
	[NIVEL] [varchar](50) NULL,
	[ID_MODULO_PADRE] [int] NULL,
	[FECHA_CREA] [varchar](50) NULL,
	[FECHA_MOD] [varchar](50) NULL,
	[USUARIO_CREA] [varchar](50) NULL,
	[USUARIO_MOD] [varchar](50) NULL,
	[ACTIVO] [int] NULL,
 CONSTRAINT [PK_MODULO] PRIMARY KEY CLUSTERED 
(
	[ID_MODULO] ASC
)WITH (PAD_INDEX = OFF, STATISTICS_NORECOMPUTE = OFF, IGNORE_DUP_KEY = OFF, ALLOW_ROW_LOCKS = ON, ALLOW_PAGE_LOCKS = ON) ON [PRIMARY]
) ON [PRIMARY]

GO
SET ANSI_PADDING OFF
GO
/****** FOREING KEYS ****/
GO
SET ANSI_PADDING OFF
GO
ALTER TABLE [USUARIO]  WITH CHECK ADD FOREIGN KEY([ID_ROL])
REFERENCES [ROL] ([ID_ROL])
GO
ALTER TABLE [PERMISO]  WITH CHECK ADD FOREIGN KEY([ID_ROL])
REFERENCES [ROL] ([ID_ROL])
GO
ALTER TABLE [PERMISO]  WITH CHECK ADD FOREIGN KEY([ID_MODULO])
REFERENCES [MODULO] ([ID_MODULO])
GO
ALTER TABLE [MODULO]  WITH CHECK ADD  FOREIGN KEY(ID_MODULO_PADRE)
REFERENCES [MODULO] (ID_MODULO)
GO
USE [master]
GO
ALTER DATABASE [PROYECTO_PROGRA3] SET  READ_WRITE 
GO

USE PROYECTO_PROGRA3;
